---

- hosts: all
  become: true
  tasks:

  - name: install updates
    apt:
      upgrade: dist
      update_cache: yes

  - name: update repository index
    apt:
      update_cache: yes
 
  - name: copy default html file for site
    tags: filesite
    copy:
      src: filesite.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
  
  -  name: add php support for apache
     apt:
       name: libapache2-mod-php
       state: latest
