
---

- hosts: all
  become: true
  tasks:

  - name: install updates
    apt:
      upgrade: dist
      update_cache: yes

  - name: update repository index
    apt:
      update_cache: yes

  -  name: start httpd for apache server
     tags: filesite_apache
     service:
       name: httpd
       state: started
       enabled: yes
     when: ansible_distribution == "Debian"

  - name: copy default html file for site
    tags: filesite
    copy:
      src: filesite.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
  
  -  name: add php support for apache
     apt:
       name: libapache2-mod-php
       state: latest

- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip
 
  - name: imstall terraform
    tags: tera
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.3.9/terraform_1.3.9_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root
