  -  name: start httpd for apache server
     tags: filesite_apache
     service:
       name: httpd
       state: started
       enabled: yes
     when: ansible_distribution == "Debian"

  - name: copy default html file for site
    tags: filesite
    copy:
      src: filesite.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
